# Generated by Django 5.2.3 on 2025-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veges', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_count',
            field=models.IntegerField(default=1),
        ),
    ]
