# Generated by Django 5.2.3 on 2025-06-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veges', '0004_department_studentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
    ]
