# Generated by Django 5.2.3 on 2025-07-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veges', '0008_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
